### ISSUE TITLE
Reopen - Text box

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2856] opened 2023-07-12 15:17 UTC
@minotogna @rfontanarosa 

Is there a way that allows us to move forward for the issue(#2714) since, as discussed with Örjan, it would be quite annoying if this issue cannot be solved and users want to paste some texts when they have already entered texts before.

**Comment by minotogna** [comment] 2023-07-12 15:21
Tomorrow I would let @sorja have a look .

**Comment by pengchenglai** [comment] 2023-07-12 15:22
Many thanks and will send you an email soon with the summary of  the meeting with Örjan.

**Comment by sorja** [comment] 2023-07-13 10:08
It seems that the issue is in the library itself (Jodit)

It is fixed now so that the pasted content is in correct position (where it's pasted) but the side effect is still that the cursor jumps to the beginning of input, but I think this is not a major issue


Edit:
For some reason the cursor keeps jumping to the first position when editing, so I am not adding the changes yet, this requires more investigation

**Closed as not planned** 2023-08-01 06:39 UTC
Labels: bug, question/investigation
