### ISSUE TITLE
Text would be overlapped after refreshing for NWFP category in table 7

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3048] opened 2023-09-11 08:39 UTC
@minotogna 

**Is your feature request related to a problem? Please describe.**
Long texts would be overlapped, after refreshing, for NWFP category in table 7(plz see below the video)
[95ce54d5-332d-4890-9762-510b41f0c866.webm](https://github.com/openforis/fra-platform/assets/99216009/3d9165d1-1b49-46f4-9836-764b1fcb8c5b)
https://github.com/openforis/fra-platform/assets/99216009/3d9165d1-1b49-46f4-9836-764b1fcb8c5b

**Describe the solution you'd like**
Not overlapped for long texts

**Priority**
Low

**Comment by minotogna** [comment] 2023-12-05 09:24
duplicate of #3264

**Closed as not planned by minotogna** 2023-12-05 09:24 UTC
