### ISSUE TITLE
Table 2b growing stock composition

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2246] opened 2023-02-16 14:36 UTC
@minotogna 
1. Some calculation of  **% of total**  does not make sense
<img width="785" alt="1" src="https://user-images.githubusercontent.com/99216009/219394227-13918676-1e5a-4d44-8407-2e2a0d5da4bd.PNG">

**Comment by pengchenglai** [comment] 2023-02-16 14:37
2. Some calculation won't update when values was changed and webpage was refreshed
<img width="785" alt="2" src="https://user-images.githubusercontent.com/99216009/219394755-00c94324-9e89-4a28-bf05-8fe3d29c29cc.PNG">

**Comment by minotogna** [comment] 2023-03-01 17:07
duplicate of #2270

**Closed as not planned by minotogna** 2023-03-01 17:07 UTC
Labels: bug
