### ISSUE TITLE
High priority - Link a file from the repository to Data sources.

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3339] opened 2023-12-21 10:08 UTC
@minotogna 

**Is your feature request related to a problem? Please describe.**
Only possible to add a link for reference. No available way to link a file from the repo to the Data Sources.

**Describe the solution you'd like**
Update: As per Anssi's suggestion
1. Upload a file in the rep
2. Make it public
3. Hover over the file name and “Copy link address”
4. Go to the National data - Data Sources section
5. Add a reference name
6. Paste the link

![image](https://github.com/openforis/fra-platform/assets/99216009/926530ca-6dcc-42fb-981b-39148ff2ca7f)

**Comment by minotogna** [comment] 2024-01-03 08:31
duplicate of #3375

**Closed as not planned by minotogna** 2024-01-03 08:31 UTC
