### ISSUE TITLE
Separate repository between FRA2020 and FRA2025

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3336] opened 2023-12-21 09:49 UTC
@minotogna 

**Is your feature request related to a problem? Please describe.**
By default, FRA 2025 should inherit what has been uploaded for FRA 2020. However, the FRA 2020 repository should not be updated with new documents from FRA 2025.

![image](https://github.com/openforis/fra-platform/assets/99216009/8a0cf6ce-ec07-4f00-831b-ae84b45d3361)

**Describe the solution you'd like**
Separate FRA2020 and FRA2025 for the repository. The FRA2020 repository should be fixed when the reporting cycle has been closed, whereas FRA2025 should inherit what has been uploaded from FRA2020 and allow the uploading of files during the ongoing FRA2025 reporting process.

**Priority**
Medium

**Comment by pengchenglai** [comment] 2023-12-21 09:50
Future uploading files should follow this pattern.

**Comment by minotogna** [comment] 2024-01-03 08:30
@pengchenglai this was already in the pipeline. we'll work on this soon ;) 
closing it as it's a duplicate of #3214

**Closed as not planned by minotogna** 2024-01-03 08:30 UTC
