### ISSUE TITLE
Click on a link to open a new webpage

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3677] opened 2024-03-29 14:03 UTC
@minotogna 

**Is your feature request related to a problem? Please describe.**
The current default redirection behavior of a link will automatically replace the current page.

**Describe the solution you'd like**
By default, 'open in a new tab' is _automatically selected_ so that when a user clicks on a link, it will open a new webpage.

**Comment by minotogna** [comment] 2024-04-04 11:37
@pengchenglai duplicate of #3666

**Closed as not planned** 2024-04-04 11:37 UTC
