### ISSUE TITLE
FRA 2020 CSV download table 7b 

### ISSUE THREAD

**Issue by AnssiSamuli** [openforis/fra-platform#2193] opened 2023-02-09 14:18 UTC
Duplicate entries

![image](https://user-images.githubusercontent.com/1213245/217837733-e0c6718c-482b-45da-9406-9428016749bc.png)

**Comment by minotogna** [comment] 2023-02-15 06:52
duplicate of #2189

**Closed as not planned by minotogna** 2023-02-15 06:52 UTC
