### ISSUE TITLE
Error message after removing a NDP

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#3091] opened 2023-09-26 15:03 UTC
@minotogna 

**Describe the bug**
Error message shows up after removing a NDP in table 1a.

**To Reproduce**
Steps to reproduce the behavior(see below the video):
1.  Remove any NDP of a given country
2. The error appears

**Expected behavior**
No error after removing the NDP.

**Screenshots**
![1](https://github.com/openforis/fra-platform/assets/99216009/1f4dfb3f-7ab7-4637-9c18-33467bef131f)
[394b3baa-ffa8-4ae9-af78-9f6ed7a73c6d.webm](https://github.com/openforis/fra-platform/assets/99216009/44a10691-1d3f-45e0-8e82-2e8e9ef7a08a)https://github.com/openforis/fra-platform/assets/99216009/44a10691-1d3f-45e0-8e82-2e8e9ef7a08a

**Priority**
Medium

**Comment by minotogna** [comment] 2023-09-26 15:19
Duplicate of #3084

**Closed as not planned by minotogna** 2023-09-26 15:19 UTC
Labels: duplicate

**Comment by pengchenglai** [comment] 2023-09-26 23:47
Good to know!
