### ISSUE TITLE
Add message colors for comments and National data

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2264] opened 2023-02-17 15:21 UTC
@minotogna 
There are no color changes if one makes comments in the **Comments** area  and **National Data**.

<img width="280" alt="1" src="https://user-images.githubusercontent.com/99216009/219694328-2ec03541-1178-46d5-bf96-b49e1bcd4848.PNG">
<img width="735" alt="2" src="https://user-images.githubusercontent.com/99216009/219694359-d8c11199-21b4-4636-bdaf-04e71105acde.PNG">

**Comment by sorja** [comment] 2023-02-17 15:37
@pengchenglai 
Thank you


For developers:

This is a issue related to how we include items in our  status and summary queries.

In this exact case the problem is here:
https://github.com/openforis/fra-platform/blob/f7528eb4ba81e36b8b375a7c36bf9db292512b79/src/client/pages/AssessmentSection/Descriptions/CommentableDescription/CommentableDescription.tsx#L55

We generate the key using this variable, but the query itself doesn't understand this, we need to somehow specify that these should be included.

The problematic queries are found here:
getReviewStatus:
https://github.com/openforis/fra-platform/blob/f7528eb4ba81e36b8b375a7c36bf9db292512b79/src/server/repository/assessmentCycle/messageTopicUser/getReviewStatus.ts#L31-L39

and getReviewSummary
https://github.com/openforis/fra-platform/blob/f7528eb4ba81e36b8b375a7c36bf9db292512b79/src/server/repository/assessmentCycle/messageTopicUser/getReviewSummary.ts#L30-L41

**Comment by minotogna** [comment] 2023-03-30 14:14
@sorja is this fixed, right? can you close this in case?

**Closed as completed** 2023-03-30 14:24 UTC
Labels: bug
