### ISSUE TITLE
Email localization issue

### ISSUE THREAD

**Issue by sorja** [openforis/fra-platform#3508] opened 2024-02-13 17:05 UTC
Received email header:
`Democratic People&#39;s  ..................................... status changed to Awaiting approval on FRA Platform`

Expected:
`Democratic People's  ..................................... status changed to Awaiting approval on FRA Platform`

**Comment by minotogna** [comment] 2024-02-14 12:55
Duplicate of #3507

**Closed as not planned by minotogna** 2024-02-14 12:55 UTC
